### ISSUE TITLE
Hydrant Status: need ability to remove photo

### ISSUE THREAD

**Issue by rssidlowski** [JMurk/Valve_Hydrant_Mobile_Issues#50]
Need the ability to remove photos that were uploaded.

**Comment by yousifmalik** [comment]
Completed and ready for testing on DEV

**Comment by rssidlowski** [comment]
I tested this and the delete is not working correctly.
Steps to recreate: 
1) opened existing inspection.
2) added photo - jellyfish
3) deleted photo - jellyfish
4) added new photo - penguins
![photodel1](https://cloud.githubusercontent.com/assets/5039052/13984496/f86973b2-f0cc-11e5-8dc8-5b4d5dfb816e.PNG)

5) view new photo - should be penguins, but shows jellyfish
![photodel2](https://cloud.githubusercontent.com/assets/5039052/13984498/fcef9268-f0cc-11e5-9f78-8ea73d4009b1.PNG)

I tried clicking the 'refresh' button and still have same result.

**Comment by rssidlowski** [comment]
To further clarify.  This works correctly if select the photo and the photo name gets refreshed.  Not clear what the 'refresh' button does, as after deleting an item and refreshing, the photo name, select image/choose files still has the 'old' item.

**Comment by yousifmalik** [comment]
Completed and ready for testing on DEV

**Comment by slmessier** [comment]
Please reference the following graphic and implement the security constraints indicated for each of the 2 cases:
1. Editor User case
2. Read Only User case

![image](https://cloud.githubusercontent.com/assets/4098544/14061915/ba1f8558-f363-11e5-999e-85ffb41b01d9.png)

**Comment by yousifmalik** [comment]
Updated DEV, Could you confirm the work flow is applied to all cases?

**Comment by slmessier** [comment]
Hi Yousif - I can confirm that the photos screen - including all of its buttons/controls - does appear correctly for the initial screen for both cases (Editor & Read-only). I am also able to successsfully upload a photo. 

However **I am unable to select a photo.currently so I am unable to test the full wortkflow. Instead of showing a slelected photo. the tap/click "sticks" until the user clicks/taps again. Please see the graphic below for an example of the issue:**
![photo_stick](https://cloud.githubusercontent.com/assets/4098544/14092594/13e9a8ee-f516-11e5-8379-19767491d4dc.gif)

**Please update the system to allow the user to make a photo selection. After the user selects a photo, the system should display the photo's metadata information, enable buttons appropriately,  and otherwise respond according to the workflow graphic (repeated below - identical to previous comment)**
![image](https://cloud.githubusercontent.com/assets/4098544/14092436/ce179d5e-f514-11e5-9639-f5816054809c.png)

**Comment by slmessier** [comment]
**Please find the following instructions below which have been updated to account for pre-existing code that could be leveraged to resolve this issue:**
1. **Equivalent functionality exists within the DEVELOPMENT  Utility Viewer Mobile App – Add Discrepancy Function.** The repository for this code can be identified within the  _City of Baltimore - EXT Development Wiki page_ - https://github.com/kcigeospatial/CityOfBaltimore/wiki/Ext-Development** Example of Utility Viewer Functionality:
   ![utilityviewer_selectphoto](https://cloud.githubusercontent.com/assets/4098544/14117523/06292674-f5b3-11e5-8828-6072326f3873.gif)
2. However, this pre-existing code does not account for the 2 security cases (Editor VS Read-only) that is required for the Valves & Hydrants application. **For Valves & Hydrants app, this functionality should be updated to satisfy the specifications within the workflow graphic (reattached without modification below):**
   ![image](https://cloud.githubusercontent.com/assets/4098544/14092436/ce179d5e-f514-11e5-9639-f5816054809c.png)

**Comment by taojun545** [comment]
@slmessier - I fixed that front-end issue on SSO before: https://github.com/JMurk/SSO-Application-Issues/issues/193. And I will fix it in the DEVELOPMENT Utility Viewer Mobile code.

**Comment by slmessier** [comment]
Hi Yousif - @taojun545 has helped me to update specifications for this issue with updated details. **Please review the instructions within most recent comment (above) and let me know if you have additional questions. Otherwise please move forward with developing the outlined updates.**

**Comment by yousifmalik** [comment]
Code updated to DEV. Please confirm the work-flow is working ok.
Hint: I used 'locate' tool -> assets and search for hydrant id 216C007760 for my testing.

I do not have access to wiki.

**Comment by slmessier** [comment]
Hi Yousif - i was able to successfully verify that the system now allow me to upload multiple photos.

However, I am still unable to fully test the associated workflow because the "sticky" map click issue prevents me from selecting a photo (as indicated below). **Please investigate the erroneous system behavior, and correct the system to select the thumbnail the user has clicked on and then otherwise following the documented workflow (above).**
![photo_stick](https://cloud.githubusercontent.com/assets/4098544/14092594/13e9a8ee-f516-11e5-8379-19767491d4dc.gif)

To recreate the issue: access the photo screen for a hydrant with an existing photo (or add a new photo), and then click/tap on an image thumbnail. After the click, the system response erroneously drags/scrolls the screen instead of displaying the thumbnail as selected.

**Comment by yousifmalik** [comment]
Code fixed and updated on DEV. Can you test the work-flow again and let me know ASAP? I need to refactor the code for these fixes.

**Comment by slmessier** [comment]
Hi Yousif - i can confirm the issue related to the mouse click/tap has been successfully validate. The photo functionality is looking a lot better at this point. However, **when attempting to test all facets of the worfklow, I still encounter the following issues that require an update:**
1. For the _Remove Photo_ workflow, the system currently does not clear the photo metadata information for the removed photo. **After the user clicks on the remove button, please update the system to also clear all text from the photo metadata text field(s).** ![image](https://cloud.githubusercontent.com/assets/4098544/14180772/7e5c4588-f732-11e5-80de-33d4f3b92728.png)
2. When 0 photo attachments exist for an inspection, the system should always resort to the "default" photo screen display (see graphic below) - even when 0 photos exist as an outcome of the user removing all previously attached photos. This currently does not occur, (the _View_ and _Remove_ buttons remain enabled for instance) **Please update the system logic to have awareness of when 0 photos exist - including the case that exists within the _Remove Workflow) using the previously defined graphic specifications** ![image](https://cloud.githubusercontent.com/assets/4098544/14181156/d7ded8f4-f733-11e5-8c80-8823572a3320.png)

**Comment by yousifmalik** [comment]
Code undated on DEV, Please confirm the changes.

**Comment by slmessier** [comment]
I was able to successfully validate the full workflow using the DEV application. Issue will be marked as "Ready for Production".

**Comment by slmessier** [comment]
@yousifmalik  and @taojun545 thank you for your patience and coordination in working through the photographs functionality. **Please note the specifications and validated photo functionality described within this issue for potential future reference when reconciling code ancestry**.
